# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles: 
    active: dev
  # 文件上传
  servlet:
     multipart:
       # 单个文件大小
       max-file-size:  10MB
       # 设置总上传的文件大小
       max-request-size:  20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: barry-jt-huang #JWT加解密使用的密钥
  expiration: 30 #JWT的超期限时间
  tokenHead: Bearer #JWT负载中拿到开头

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /dev-api

sys:
  # 名称
  name: Demo by barry
  # 版本
  version: 0.0.1
  # 版权年份
  copyrightYear: 2020
  # 文件路径
  profile: D:\upload
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math

secure:
  ignored:
    permitAllUrls: #安全路径白名单
      - /**/*.png
      - /**/*.ico
      - /*.html
      - /**/*.html
      - /**/*.css
      - /**/*.js
      - /dev-api/tool/swagger
      - /system/dict/data/**
    anonymousUrls:
      - /login
      - /profile/**
      - /common/download**
      - /common/download/resource**
      - /swagger-ui.html
      - /swagger-resources/**
      - /webjars/**
      - /*/api-docs
      - /druid/**
      - /captchaImage
      - /system/user/register

mybatis:
  mapper-locations:
    - classpath*:dao/*.xml
    - classpath*:com/**/mapper/*.xml